version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: farazshah350/node-app
    environment:
      - PORT=3001
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=faraz
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
